CREATE OR REPLACE VIEW `hive_metastore`.`default`.`paas_tracking_card_metric_view` AS
SELECT
  CAST(DATE(session_start_date_time) AS DATE) AS `Date`,
  DATE_TRUNC('MONTH', CAST(DATE(session_start_date_time) AS DATE)) AS `Month(Date)`,
  `os_platform` AS `Os Platform`,
  `app_version` AS `App Version`,
  `geo_country_code` AS `Geo Country Code`,
  `is_hpid_signed_in` AS `Is Hpid Signed In`,
  `is_oobe_complete` AS `Is Oobe Complete`,
  `is_aip_setup_complete` AS `Is Aip Setup Complete`,
  `is_clicked_support` AS `Is Clicked Support`,
  `is_clicked_aip_order_accord` AS `Is Clicked Aip Order Accord`,
  `is_clicked_aip_order_accordian_order_confirmed` AS `Is Clicked Aip Order Accordian Order Confirmed`,
  `is_ows_start` AS `Is Ows Start`,
  `is_clicked_aip_order_accordian_order_processing` AS `Is Clicked Aip Order Accordian Order Processing`,
  `is_oobe_support_session` AS `Is Oobe Support Session`,
  `is_aip_setup_start` AS `Is Aip Setup Start`,
  `is_clicked_aip_order_accordian_order_shipped` AS `Is Clicked Aip Order Accordian Order Shipped`,
  `aip_device_uuid` AS `Aip Device Uuid`,
  `session_start_date_time` AS `Session Start Date Time`,
  `max_total_printer_count` AS `Max Total Printer Count`,
  `is_associated_device` AS `Is Associated Device`,
  `total_accessory_count` AS `Total Accessory Count`,
  `max_total_accessory_count` AS `Max Total Accessory Count`,
  `is_viewed_aip_tracking_card` AS `Is Viewed Aip Tracking Card`,
  `is_clicked_order_processing_pill` AS `Is Clicked Order Processing Pill`,
  `is_clicked_track_delivery` AS `Is Clicked Track Delivery`,
  `is_clicked_order_shipped_pill` AS `Is Clicked Order Shipped Pill`,
  `app_package_deployed_uuid` AS `App Package Deployed Uuid`,
  `app_name` AS `App Name`,
  `is_clicked_aip_order_accordian` AS `Is Clicked Aip Order Accordian`,
  -- Measures (Formulas)
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_complete_setup THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_complete_setup THEN app_package_deployed_uuid END) END AS `Clicked Complete Setup`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_aip_order_accordian THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_aip_order_accordian THEN app_package_deployed_uuid END) END AS `Clicked Expand`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_order_confirmation THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_order_confirmation THEN app_package_deployed_uuid END) END AS `Clicked Order Confirmation`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_order_processing THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_order_processing THEN app_package_deployed_uuid END) END AS `Clicked Order Processing`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_track_delivery THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_track_delivery THEN app_package_deployed_uuid END) END AS `Clicked Track Delivery`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_confirmed THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_confirmed THEN app_package_deployed_uuid END) END AS `Confirmed`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_delivered THEN device_app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_delivered THEN device_app_package_deployed_uuid END) END AS `Delivered`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_order_delivered_pill THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_order_delivered_pill THEN app_package_deployed_uuid END) END AS `Delivered - Pill`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_delivered AND is_aip_setup_complete THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_delivered AND is_aip_setup_complete THEN app_package_deployed_uuid END) END AS `Onboarded`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_order_confirmation_pill THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_order_confirmation_pill THEN app_package_deployed_uuid END) END AS `Order Confirmed - Pill`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_processing THEN device_app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_processing THEN device_app_package_deployed_uuid END) END AS `Processed`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_order_processing_pill THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_order_processing_pill THEN app_package_deployed_uuid END) END AS `Processing - Pill`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_shipped THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_shipped THEN app_package_deployed_uuid END) END AS `Shipped`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_clicked_order_shipped_pill THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_clicked_order_shipped_pill THEN app_package_deployed_uuid END) END AS `Shipped - Pill`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_delivered AND is_oobe_support_session THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card_order_delivered AND is_oobe_support_session THEN app_package_deployed_uuid END) END AS `Support Cases`,
  CASE WHEN COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card THEN app_package_deployed_uuid END) = 0 THEN NULL ELSE COUNT(DISTINCT CASE WHEN is_viewed_aip_tracking_card THEN app_package_deployed_uuid END) END AS `Viewed PaaS Tracking Card`
FROM `hive_metastore`.`default`.`paas_tracking_card`
GROUP BY
  CAST(DATE(session_start_date_time) AS DATE),
  DATE_TRUNC('MONTH', CAST(DATE(session_start_date_time) AS DATE)),
  `os_platform`,
  `app_version`,
  `geo_country_code`,
  `is_hpid_signed_in`,
  `is_oobe_complete`,
  `is_aip_setup_complete`,
  `is_clicked_support`,
  `is_clicked_aip_order_accord`,
  `is_clicked_aip_order_accordian_order_confirmed`,
  `is_ows_start`,
  `is_clicked_aip_order_accordian_order_processing`,
  `is_oobe_support_session`,
  `is_aip_setup_start`,
  `is_clicked_aip_order_accordian_order_shipped`,
  `aip_device_uuid`,
  `session_start_date_time`,
  `max_total_printer_count`,
  `is_associated_device`,
  `total_accessory_count`,
  `max_total_accessory_count`,
  `is_viewed_aip_tracking_card`,
  `is_clicked_order_processing_pill`,
  `is_clicked_track_delivery`,
  `is_clicked_order_shipped_pill`,
  `app_package_deployed_uuid`,
  `app_name`,
  `is_clicked_aip_order_accordian`
;
