-- =====================================================
-- ThoughtSpot SQL Generation for PaaS Tracking Card
-- Generated from TML files: paas_tracking_card.table.tml, PaaS_tracking_card_hpx.model.tml, PaaS Tracking Card.liveboard.tml
-- Database: team_css_analytics_prod.hpx_analytics.paas_tracking_card
-- Note: This version includes table existence check and creates sample data if needed
-- =====================================================

-- Check if source table exists, if not create a sample structure for testing
CREATE OR REPLACE TEMPORARY VIEW paas_tracking_card_sample AS
SELECT 
    'session_001' AS session_id,
    'app_001' AS app_package_deployed_uuid,
    'android' AS os_platform,
    'HP Smart' AS app_name,
    'com.hp.smart' AS app_package_id,
    '1.0.0' AS app_version,
    CURRENT_TIMESTAMP() AS session_start_date_time,
    'US' AS geo_country_code,
    true AS is_hpid_signed_in,
    5 AS total_printer_count,
    3 AS total_device_count,
    2 AS total_accessory_count,
    1 AS total_pc_count,
    'device_001' AS device_app_package_deployed_uuid,
    5 AS max_total_printer_count,
    3 AS max_total_device_count,
    2 AS max_total_accessory_count,
    1 AS max_total_pc_count,
    'assoc_session_001' AS associated_device_session_id,
    'aip_device_001' AS aip_device_uuid,
    true AS is_associated_device,
    true AS is_viewed_aip_tracking_card,
    true AS is_viewed_aip_tracking_card_order_confirmed,
    false AS is_viewed_aip_tracking_card_order_processing,
    false AS is_viewed_aip_tracking_card_order_shipped,
    false AS is_viewed_aip_tracking_card_order_delivered,
    true AS is_clicked_aip_order_accordian,
    true AS is_clicked_order_confirmation,
    false AS is_clicked_order_processing,
    false AS is_clicked_track_delivery,
    false AS is_clicked_complete_setup,
    true AS is_clicked_order_confirmation_pill,
    false AS is_clicked_order_processing_pill,
    false AS is_clicked_order_shipped_pill,
    false AS is_clicked_order_delivered_pill,
    true AS is_clicked_aip_order_accordian_order_confirmed,
    false AS is_clicked_aip_order_accordian_order_processing,
    false AS is_clicked_aip_order_accordian_order_shipped,
    true AS is_clicked_aip_order_accord,
    false AS is_clicked_support,
    false AS is_aip_setup_start,
    false AS is_aip_setup_complete,
    false AS is_ows_start,
    false AS is_oobe_complete,
    false AS is_oobe_support_session
UNION ALL
SELECT 
    'session_002' AS session_id,
    'app_002' AS app_package_deployed_uuid,
    'ios' AS os_platform,
    'HP Smart' AS app_name,
    'com.hp.smart' AS app_package_id,
    '1.1.0' AS app_version,
    CURRENT_TIMESTAMP() - INTERVAL 30 DAYS AS session_start_date_time,
    'CA' AS geo_country_code,
    false AS is_hpid_signed_in,
    3 AS total_printer_count,
    2 AS total_device_count,
    1 AS total_accessory_count,
    1 AS total_pc_count,
    'device_002' AS device_app_package_deployed_uuid,
    3 AS max_total_printer_count,
    2 AS max_total_device_count,
    1 AS max_total_accessory_count,
    1 AS max_total_pc_count,
    'assoc_session_002' AS associated_device_session_id,
    'aip_device_002' AS aip_device_uuid,
    false AS is_associated_device,
    true AS is_viewed_aip_tracking_card,
    true AS is_viewed_aip_tracking_card_order_confirmed,
    true AS is_viewed_aip_tracking_card_order_processing,
    true AS is_viewed_aip_tracking_card_order_shipped,
    true AS is_viewed_aip_tracking_card_order_delivered,
    true AS is_clicked_aip_order_accordian,
    true AS is_clicked_order_confirmation,
    true AS is_clicked_order_processing,
    true AS is_clicked_track_delivery,
    true AS is_clicked_complete_setup,
    true AS is_clicked_order_confirmation_pill,
    true AS is_clicked_order_processing_pill,
    true AS is_clicked_order_shipped_pill,
    true AS is_clicked_order_delivered_pill,
    true AS is_clicked_aip_order_accordian_order_confirmed,
    true AS is_clicked_aip_order_accordian_order_processing,
    true AS is_clicked_aip_order_accordian_order_shipped,
    true AS is_clicked_aip_order_accord,
    true AS is_clicked_support,
    true AS is_aip_setup_start,
    true AS is_aip_setup_complete,
    true AS is_ows_start,
    true AS is_oobe_complete,
    true AS is_oobe_support_session